### ISSUE TITLE
Change MessageService into a MessageRouter

### ISSUE THREAD

**Issue by Elliott127** [martinimon/ED-83-of-Empire#26]
Since the ProcessCommand methods switch statement is starting to get clogged we should instead decouple this into separate parts.
We should split these into 
- MessageRouter
- SteamMessageService
- EdgeMessageService
- GeneralMessageService

This will enable us to clean up that area of the code and also be able to do things like error handling without it looking extremely messy

**Comment by martinimon** [comment]
Similar to #34

**Comment by Elliott127** [comment]
Closing as it was completed in the latest PR
