### ISSUE TITLE
Enhance SteamService to use specific methods instead of complex switch statements with all the logic

### ISSUE THREAD

**Issue by martinimon** [martinimon/ED-83-of-Empire#38]
The SteamService currently has a lot of the logic/command processing in a single switch
ie 
game: { // game code}
gr: //gr code

instead of seperate methods that are called by the switch. This will help reduce cognitive complexity.

**Comment by Elliott127** [comment]
Can you please expand on this as I am slightly confused

**Comment by Elliott127** [comment]
Ahhh I see what you mean now.
Yes we should break these down into methods. I think I will keep the methods scoped at the message handler level. 
The switch statement will inevitably get messy if we also try to handle multiple cases for the same method as well.

Will need to discuss whether multiple choices for example "gr" and "requestGame" to run the same command are worth doing.
